### ISSUE TITLE
ncurses based programs fail to render properly on terminal resize

### ISSUE THREAD

**Issue by jruffet** [lxc/lxc#1016]
I'm using LXC from debian-backports : 2.0.0-3~bpo8+1
Since this version (1.1.5 works fine), when using ncurses based programs like htop or weechat, rendering is behaving incorrectly when resizing the terminal.
I've tested 2 different configurations (default debian unprivileged and custom privileged), both behave the same.

**Comment by stgraber** [comment]
@brauner something to do with the pts proxy?

**Comment by brauner** [comment]
On Tue, May 10, 2016 at 09:57:10AM -0700, sativouf wrote:
> I'm using LXC from debian-backports : 2.0.0-3~bpo8+1

This should be fixed in the master branch by commit:
https://github.com/lxc/lxc/commit/a7c97a40ec3939047157633b23e6015c0d5c78ce

I don't know if the Debian backports already include this. If not or if you're
not sure could you try with current master?

**Comment by evgeni** [comment]
@brauner no, this patch was not backported. I think a 2.0.1 should come up soon? ;)

**Comment by brauner** [comment]
Talk to @stgraber about these things. ;)

**Comment by stgraber** [comment]
Yeah, I need to finish cherry-picking all the fixes and tag a 2.0.1. Maybe this week if all goes well.

**Comment by evgeni** [comment]
@sativouf this is should be fixed since 2.0.1, can you verify please?

**Comment by sativouf** [comment]
Using 2.0.5 from debian backports, I still have issues when resizing the terminal.
Although it's better than before : weechat resizes correctly, but htop does not.

**Comment by brauner** [comment]
Have you tried by setting `export TERM=xterm` in the container attached shell? Also, this could be caused by `glibc` incorrectly reporting back `no tty` when actually it is on a tty. This is a bug we are currently trying to fix upstream in `glibc`.

**Comment by sativouf** [comment]
@brauner no difference with `export TERM=xterm`

**Comment by brauner** [comment]
This should be fixed in liblxc master where we moved pty allocation into the api and have reworked the whole pty handling code. If this is still a problem, please re-open.
