### ISSUE TITLE
lxc-checkpoint fails in ubuntu 

### ISSUE THREAD

**Issue by dinuni** [lxc/lxc#1213]
My kernel  is  4.2.0-27-generic - Ubuntu 14.04.4 LTS.

when I try to checkpoint , using the following command `sudo lxc-checkpoint -s -D /tmp/checkpoint -n u1`
Im getting this error 

```
Will skip in-flight TCP connections
lxc-checkpoint: u1: criu.c: do_dump: 998 dump failed with 1
Checkpointing u1 failed.
```

dump.log gives  the following error output 

`Error (criu/ptrace.c:64): suspending seccomp failed: Invalid argument
Error (criu/ptrace.c:54): Unable to detach from 14540: No such process
Error (criu/cr-dump.c:1628): Dumping FAILED.`

When use `criu check` command it gives the output as 
`Looks good.`

`ls -al /proc/self/ns`
total 0
dr-x--x--x 2 root root 0 Sep 28 15:12 .
dr-xr-xr-x 9 root root 0 Sep 28 15:12 ..
lrwxrwxrwx 1 root root 0 Sep 28 15:12 ipc -> ipc:[4026531839]
lrwxrwxrwx 1 root root 0 Sep 28 15:12 mnt -> mnt:[4026531840]
lrwxrwxrwx 1 root root 0 Sep 28 15:12 net -> net:[4026531957]
lrwxrwxrwx 1 root root 0 Sep 28 15:12 pid -> pid:[4026531836]
lrwxrwxrwx 1 root root 0 Sep 28 15:12 user -> user:[4026531837]
lrwxrwxrwx 1 root root 0 Sep 28 15:12 uts -> uts:[4026531838]

 Do you have any idea how to fix this ?
Thanks

**Comment by dinuni** [comment]
My kernel  is  4.2.0-27-generic - Ubuntu 14.04.4 LTS.

when I try to checkpoint , using the following command `sudo lxc-checkpoint -s -D /tmp/checkpoint -n u1`
Im getting this error 

```
Will skip in-flight TCP connections
lxc-checkpoint: u1: criu.c: do_dump: 998 dump failed with 1
Checkpointing u1 failed.
```

dump.log gives  the following error output 

`Error (criu/ptrace.c:64): suspending seccomp failed: Invalid argument
Error (criu/ptrace.c:54): Unable to detach from 14540: No such process
Error (criu/cr-dump.c:1628): Dumping FAILED.`

When use `criu check` command it gives the output as 
`Looks good.`

 Do you have any idea how to fix this ?
Thanks

**Comment by brauner** [comment]
This is likely a problem with the kernel version you're using. We have seen similar problems in https://github.com/xemul/criu/issues/112 and https://github.com/xemul/criu/issues/199. Please upgrade your kernel if possible and try again.

**Comment by dinuni** [comment]
great , thanks , it works with ubuntu 4.4.2

**Comment by dinuni** [comment]
My kernel is 4.4.2 - Ubuntu 14.04.4 LTS. 

When I re-install criu , `criu check` command returns the following error 
Error (cr-check.c:833): cgroupns not supported. This is not fatal.

`sudo lxc-checkpoint -s -D /tmp/checkpoint -n u1 -v `

```
lxc-checkpoint: criu.c: do_dump: 879 dump failed with 1
Checkpointing u1 failed.

```
Now the error is same but the error line number is different. 
Before re-installing criu , everything worked well. 
Do you have any idea how to fix this ?
Thanks

**Comment by brauner** [comment]
Can you please paste/append the `criu` logs. They should be found in `/tmp/checkpoint`.

**Comment by dinuni** [comment]
Please find the shared dump file 
[](https://drive.google.com/file/d/0B2XDUgA404_3dkNmUENZdG5jeHM/view?usp=sharing)
Thanks

**Comment by brauner** [comment]
This is something @tych0 might be better equipped to answer right now.

**Comment by tych0** [comment]
What version of liblxc are you on? What is your container's configuration?

**Comment by dinuni** [comment]
I hope liblxc version can get using this command `lxc-start --version`
2.0.0

`lxc-info -n u1` , u1 is based on ubuntu template 
Name:           u1
State:          RUNNING
PID:            2669
IP:             10.0.3.83
CPU use:        1.86 seconds
BlkIO use:      37.67 MiB
Memory use:     26.54 MiB
KMem use:       0 bytes
Link:           vethK3PPL1
 TX bytes:      1.96 KiB
 RX bytes:      2.52 KiB
 Total bytes:   4.48 KiB

**Comment by tych0** [comment]
2.0.0 is quite old, as is criu 2.0, can you upgrade to a newer version of each and see if it is reproducible?

By configuration, I meant the contents of the lxc.conf file for the container. Mostly I'm curious about your `lxc.console` and `lxc.tty` lines.

**Comment by dinuni** [comment]
I installed lxc 2.0.5 and criu is 2.0
here is the content for the configuration file 
# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# Container specific configuration
lxc.rootfs = /var/lib/lxc/u1/rootfs
lxc.utsname = u1
lxc.arch = amd64

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:fb:9d:25
lxc.aa_allow_incomplete = 1

# hax for criu
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm

**Comment by brauner** [comment]
As the message states, this warning can be ignored and is non-fatal. Live-migration should still work.

**Comment by dinuni** [comment]
But in the criu dump gives error, as shown below ,
so checkpointing fails 

(01.910137) sk unix: Dumping external sockets
(01.910154) Error (tty.c:351): tty: Found slave peer index 1 without correspond master peer
(01.910395) Unlock network
(01.910404) Running network-unlock scripts
(01.914105) Unfreezing tasks into 1
(01.914123)     Unseizing 25300 into 1
(01.915703)     Unseizing 25360 into 1
(01.915759)     Unseizing 25464 into 1
(01.915794)     Unseizing 25491 into 1
(01.915847)     Unseizing 25492 into 1
(01.915859)     Unseizing 25494 into 1
(01.915865)     Unseizing 25511 into 1
(01.915871)     Unseizing 25512 into 1
(01.915883)     Unseizing 25514 into 1
(01.915894)     Unseizing 25520 into 1
(01.915904)     Unseizing 25569 into 1
(01.915917)     Unseizing 25581 into 1
(01.915943)     Unseizing 25973 into 1
(01.916036) Error (cr-dump.c:1600): Dumping FAILED.

**Comment by brauner** [comment]
Yeah, but this should be unrelated to whether your kernel supports cgroup namespaces. :)
We need a little more information:

- Please start the container your tryting to c/r with `lxc-start -n c -l DEBUG -o c.log`, perform the migration and append the `c.log` file here.
- Please append the containers configuration file.
- Please gather the criu logs and append them here.
Thanks. :)

**Comment by tych0** [comment]
I think you're probably hitting a bug that was fixed around the 2.4 timeframe; I can't find a link to the exact patch right offhand. Can you try CRIU 2.6 or 2.7?

**Comment by dinuni** [comment]
I changed the versions of both criu and lxc 
criu -> 2.7
lxc -> 2.0.5

checkpointing fails giving this error (Error (criu/cr-dump.c:1636): Dumping FAILED)
I have shared all the dump files,(https://drive.google.com/drive/folders/0B2XDUgA404_3ckZmZC1EUXZoODQ?usp=sharing)
1. container start log 
2.container config file 
3. criu log file 
Thanks.

**Comment by tych0** [comment]
Hi,

So from your log, @brauner pointed out:

```
      lxc-start 20161101150622.396 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/0' (9/12)
      lxc-start 20161101150622.396 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/1' (13/14)
      lxc-start 20161101150622.396 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/2' (15/16)
      lxc-start 20161101150622.396 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/3' (17/18)
      lxc-start 20161101150622.396 INFO     lxc_conf - conf.c:lxc_create_tty:3321 - tty's configured
      lxc-start 20161101150622.396 INFO     lxc_conf - conf.c:setup_tty:995 - 4 tty(s) has been setup
```

which I think means that you haven't set `lxc.tty = 0` for this container. It looks like this is a legit bug in that with non-zero lxc.tty settings, migration fails. However, if you set `lxc.tty = 0`, it should checkpoint. Can you give that a try?

**Comment by dinuni** [comment]
I had two config files for the same container in two different locations 
1. /var/lib/lxc/u2 
2./usr/local/var/lib/lxc/u2/
initially I have updated in location 1, and was getting all above errors for checkpointing. Then I started editing the config file in the 2nd location,  added those lines in this config file . 

Now I can checkpoint and restore without any issue , thanks alot !

**Comment by davidebaldini** [comment]
Hello,

I skimmed thru the PRs but couldn't find if this has been addressed. Is `lxc.tty = 0` still required?

**Comment by tych0** [comment]
Yes, on lxc 2.0 and greater this is fixed.

**Comment by loth** [comment]
Hello, I am still getting this error with LXC 2.0.7-0ubuntu1~16.04.2 and criu 2.6-1ubuntu1~ubuntu16.04.2

`Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
Warn  (criu/arch/x86/crtools.c:133): Will restore 157265 with interrupted system call
tar: ./systemd/journal/syslog: socket ignored
tar: ./systemd/journal/dev-log: socket ignored
tar: ./systemd/journal/socket: socket ignored
tar: ./systemd/journal/stdout: socket ignored
tar: ./systemd/private: socket ignored
tar: ./systemd/notify: socket ignored
Error (criu/tty.c:381): tty: Found slave peer index 0 without correspond master peer
Error (criu/cr-dump.c:1628): Dumping FAILED.`

Container config:
`# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.start.auto = 1
lxc.start.delay = 5
lxc.cgroup.devices.allow = b 7:* rwm # allow loop devices
lxc.cgroup.devices.allow = c 10:237 rwm # allow loop-control device
lxc.autodev = 1
lxc.hook.autodev = /etc/lxc/mount-loop-hook.sh
lxc.rootfs = /var/lib/lxc/test01/rootfs
lxc.rootfs.backend = dir
lxc.utsname = test01

# Network configuration
lxc.network.type = empty
lxc.network.flags = up`

**Comment by brauner** [comment]
@loth, as a temporary workaround you need to et `lxc.tty=0` in the container's config. This is described in the thread further up.
