### ISSUE TITLE
Failed to attach "lxcbr0" to openvswitch bridge "vethKNARGM"

### ISSUE THREAD

**Issue by karta0807913** [lxc/lxc#2856]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Linux tegra-ubuntu
 * Distribution version: 4.4.38
 * The output of
   * `lxc-start --version`
```
3.0.3
```
   * `lxc-checkconfig`
```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/freezer
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/debug
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices

Cgroup v2 mount points: 


Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig
```
   * `uname -a`
```
Linux tegra-ubuntu 4.4.38 #2 SMP PREEMPT Wed Feb 13 16:34:18 CST 2019 aarch64 aarch64 aarch64 GNU/Linux
```
   * `cat /proc/self/cgroup`
```
11:devices:/user.slice
10:memory:/user.slice
9:debug:/
8:net_cls,net_prio:/
7:freezer:/
6:perf_event:/
5:cpuset:/
4:pids:/user.slice/user-1001.slice
3:cpu,cpuacct:/user.slice
2:blkio:/user.slice
1:name=systemd:/user.slice/user-1001.slice/session-c1.scope
```
   * `cat /proc/1/mounts`
```
/dev/root / ext4 rw,relatime,data=ordered 0 0
devtmpfs /dev devtmpfs rw,relatime,size=7967788k,nr_inodes=1991947,mode=755 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/debug cgroup rw,nosuid,nodev,noexec,relatime,debug 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
tmpfs /run/user/1001 tmpfs rw,nosuid,nodev,relatime,size=803460k,mode=700,uid=1001,gid=1001 0 0
gvfsd-fuse /run/user/1001/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1001,group_id=1001 0 0
```
# Issue description

I build lxc from source but I get this error
```
Failed to attach "lxcbr0" to openvswitch bridge "vethKNARGM"
```

`lxc-net.service` and `lxc.service` are working 
```
● lxc-net.service - LXC network bridge setup
   Loaded: loaded (/lib/systemd/system/lxc-net.service; enabled; vendor preset: enabled)
```
```
● lxc.service - LXC Container Initialization and Autoboot Code
   Loaded: loaded (/lib/systemd/system/lxc.service; enabled; vendor preset: enab
   Active: active (exited) since Fri 2019-02-15 21:44:35 CST; 2h 26min ago
```

my `/usr/local/libexec/lxc/lxc-net`
```
#!/bin/sh -

distrosysconfdir="/usr/local/etc/default"
varrun="/run/lxc"
varlib="/usr/local/var/lib"

# These can be overridden in /usr/local/etc/default/lxc
#   or in /usr/local/etc/default/lxc-net

USE_LXC_BRIDGE="true"
LXC_BRIDGE="lxcbr0"
LXC_BRIDGE_MAC="00:16:3e:00:00:00"
LXC_ADDR="10.0.3.1"
LXC_NETMASK="255.255.255.0"
LXC_NETWORK="10.0.3.0/24"
LXC_DHCP_RANGE="10.0.3.2,10.0.3.254"
LXC_DHCP_MAX="253"
LXC_DHCP_CONFILE=""
LXC_DHCP_PING="true"
LXC_DOMAIN=""

LXC_IPV6_ADDR=""
LXC_IPV6_MASK=""
LXC_IPV6_NETWORK=""
LXC_IPV6_NAT="false"
# ...
```

and `/usr/local/etc/lxc/default.conf`

```
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
```

log
```
lxc-start my-container 20190215161757.366 WARN     initutils - initutils.c:setproctitle:324 - Invalid argument - Failed to set cmdline
lxc-start my-container 20190215161757.366 INFO     lxccontainer - lxccontainer.c:do_lxcapi_start:959 - Failed to set process title to [lxc monitor] /usr/local/var/lib/lxc my-container
lxc-start my-container 20190215161757.367 INFO     start - start.c:lxc_check_inherited:314 - Closed inherited fd 3
lxc-start my-container 20190215161757.367 INFO     lsm - lsm/lsm.c:lsm_init:50 - LSM security driver nop
lxc-start my-container 20190215161757.369 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:707 - No such device - The process does not have a controlling terminal
lxc-start my-container 20190215161757.370 INFO     start - start.c:lxc_init:897 - Container "my-container" is initialized
lxc-start my-container 20190215161757.385 INFO     network - network.c:instantiate_veth:150 - Retrieved mtu 1500 from veth3X4EG8
lxc-start my-container 20190215161757.386 ERROR    utils - utils.c:run_command:1615 - Failed to exec command
lxc-start my-container 20190215161757.387 ERROR    network - network.c:lxc_ovs_attach_bridge:1887 - Failed to attach "lxcbr0" to openvswitch bridge "veth41DN6M": lxc-start: my-container: utils.c: run_command: 1615 Failed to exec command
lxc-start my-container 20190215161757.387 ERROR    network - network.c:instantiate_veth:172 - Operation not permitted - Failed to attach "veth41DN6M" to bridge "lxcbr0"
lxc-start my-container 20190215161757.414 ERROR    network - network.c:lxc_create_network_priv:2457 - Failed to create network device
lxc-start my-container 20190215161757.414 ERROR    start - start.c:lxc_spawn:1626 - Failed to create the network
lxc-start my-container 20190215161757.414 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "my-container"
lxc-start my-container 20190215161757.415 DEBUG    lxccontainer - lxccontainer.c:wait_on_daemonized_start:830 - First child 8030 exited
lxc-start my-container 20190215161757.415 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "STOPPING" instead of "RUNNING"
lxc-start my-container 20190215161757.415 ERROR    lxc_start - tools/lxc_start.c:main:330 - The container failed to start
lxc-start my-container 20190215161757.415 ERROR    lxc_start - tools/lxc_start.c:main:333 - To get more details, run the container in foreground mode
lxc-start my-container 20190215161757.415 ERROR    lxc_start - tools/lxc_start.c:main:336 - Additional information can be obtained by setting the --logfile and --logpriority options
```

# Steps to reproduce

 1. `lxc-create -t download -n my-container`
 2. `lxc-start -n my-container -d`

# Information to attach

 - [ ] any relevant kernel output (`dmesg`) 
 - [x] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [x] the containers configuration file

P.S second information 
* `lxc-start -n <c> -l <log> -o DEBUG`(X)
* `lxc-start -n <c> -o <log> -l DEBUG`(O)
 Greetings !

**Comment by stgraber** [comment]
Can you show the config of the container itself? (/var/lib/lxc/my-container/config)?

**Comment by karta0807913** [comment]
`/usr/local/var/lib/lxc/my-container`
```
# Template used to create this container: /usr/local/share/lxc/templates/lxc-download
# Parameters passed to the template:
# Template script checksum (SHA-1): 161cea1217a1fb9b5c968b27bb92a0965de39eb3
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/local/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Distribution configuration
lxc.include = /usr/local/share/lxc/config/common.conf

# For Ubuntu 14.04
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir,optional 0 0
lxc.arch = linux64

# Container specific configuration
lxc.rootfs.path = dir:/usr/local/var/lib/lxc/my-container/rootfs
lxc.uts.name = my-container

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:47:95:c1
```

**Comment by stgraber** [comment]
Can you try doing (as root):
 - ip link add blah0 type veth peer blah1
 - ip link del blah0

For good measure, `ifconfig lxcbr0` would also be useful (if those commands above succeed).

**Comment by karta0807913** [comment]
these command success

`ifconfig lxcbr0` return
```
lxcbr0: error fetching interface information: Device not found
```
 and I don't see `lxcbr0` in my `ifconfig`
```
$ ifconfig -a | sed 's/[ \t].*//;/^\(lo\|\)$/d'
dummy0
eth0
l4tbr0
tunl0
usb0
usb1
wlan0
```
Greetings !

**Comment by stgraber** [comment]
Ok, so yeah, the issue is that your network bridge didn't start properly. You could try manually running lxc-net to see what's going on with that.

**Comment by karta0807913** [comment]
I didn't find the `lxc-net` command, so I restarted my `lxc-net.service` and used `journalctl` trace output.
```
$ sudo systemctl stop lxc-net.service
$ sudo systemctl start lxc-net.service
```
```
$ journalctl -u lxc-net.service -f
Feb 16 17:49:44 tegra-ubuntu systemd[1]: Stopped LXC network bridge setup.
Feb 16 17:50:19 tegra-ubuntu systemd[1]: Stopped LXC network bridge setup.
Feb 16 17:50:25 tegra-ubuntu systemd[1]: Starting LXC network bridge setup...
Feb 16 17:50:25 tegra-ubuntu systemd[1]: Started LXC network bridge setup.
```
```
$ systemctl status lxc-net.service 
● lxc-net.service - LXC network bridge setup
   Loaded: loaded (/lib/systemd/system/lxc-net.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2019-02-16 17:50:25 CST; 2min 57s ago
  Process: 19208 ExecStop=/usr/local/libexec/lxc/lxc-net stop (code=exited, status=0/SUCCESS)
  Process: 19247 ExecStart=/usr/local/libexec/lxc/lxc-net start (code=exited, status=0/SUCCESS)
 Main PID: 19247 (code=exited, status=0/SUCCESS)

Feb 16 17:50:25 tegra-ubuntu systemd[1]: Starting LXC network bridge setup...
Feb 16 17:50:25 tegra-ubuntu systemd[1]: Started LXC network bridge setup.
```
I didn't see any special

Greetings !

**Comment by adrien-n** [comment]
Hi,

I originally came here because I had the same issue but I've now solved it.

For some reasons, I was attempting to attach to a bridge that didn't exist (it used to be created but then I changed a script and rebooted). The error message seems to be particularly misleading.

The check in `is_ovs_bridge()` in `network.c` seems too simple:

    snprintf(brdirname, 22 +IFNAMSIZ + 1, "/sys/class/net/%s/bridge", bridge);
    if (stat(brdirname, &sb) == -1 && errno == ENOENT)

and there seems to be no earlier check that `/sys/class/net/%s` exists. As far as I understand, a missing interface will be treated as an ovs bridge and confusion will ensue.

**Comment by NaruFGT** [comment]
I believe the source of this issue is that in some distributions /etc/sysconfig/lxc-net is missing and /etc/sysconfig/lxc contains
`USE_LXC_BRIDGE="false"  # overridden in lxc-net`
Changing this to true fixed this issue for me.

The lxc-net.service wrapper and the libexec/lxc/lxc-net script should probably be modified to provide useful feedback regarding the configuration, as most (all?) containers will fail to start in their vanilla configuration if the lxc bridge is not running. 
I found the same results as @karta0807913 with no useful syslog messages (journalctl -u lxc-net.service)
It was only because of the useful comments within the lxc-net script that I found the issue.
`# These can be overridden in /etc/sysconfig/lxc
#   or in /etc/sysconfig/lxc-net`

**Comment by brauner** [comment]
This logic is fixed in LXC master and will be included in the 4.0 release.

**Comment by yaneony** [comment]
And where is solution? There is no 4.0 for Debian... and the problem still exist.

**Comment by danielcynerio** [comment]
At least for me it  worked to edit the file /etc/sysconfig/lxc-net and put in:
`USE_LXC_BRIDGE="true"`

**Comment by brauner** [comment]
> And where is solution? There is no 4.0 for Debian... and the problem still exist.

It should've been cherry-picked into stable-3.0 already. Once @stgraber  cuts a new release Debian should get it too.
