### ISSUE TITLE
lxc-start fails in 3.0.3 on Ubuntu 18.04.2 : Failed to mount rootfs [...] onto "/usr/lib/x86_64-linux-g nu/lxc" with options "(null)"

### ISSUE THREAD

**Issue by scritchplouf** [lxc/lxc#3016]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04.2 LTS amd64
 * The output of
   * `lxc-start --version` : 3.0.3
   * `lxc-checkconfig`

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.15.0-50-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/memory
/sys/fs/cgroup/rdma
/sys/fs/cgroup/blkio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/hugetlb

Cgroup v2 mount points:
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
Linux zlebia 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`
12:hugetlb:/
11:freezer:/user/clem/0
10:blkio:/user.slice
9:rdma:/
8:memory:/user.slice
7:cpuset:/
6:perf_event:/
5:net_cls,net_prio:/
4:pids:/user.slice/user-1000.slice/session-13.scope
3:cpu,cpuacct:/user.slice
2:devices:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-13.scope
0::/user.slice/user-1000.slice/session-13.scope

   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,relatime 0 0
proc /proc proc rw,relatime 0 0
udev /dev devtmpfs rw,relatime,size=1980504k,nr_inodes=495126,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=402224k,mode=755 0 0
/dev/sda2 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14424 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
/dev/sda3 /home ext4 rw,relatime,data=ordered 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=402220k,mode=700,uid=1000,gid=1000 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0

# Issue description

After an Ubuntu upgrade from 16.04 to 18.04, the existing unprivileged LXC containers, created and used with previons versions of LXC, won't start, with the following error :

lxc-start: u-dns: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
lxc-start: u-dns: tools/lxc_start.c: main: 330 The container failed to start
lxc-start: u-dns: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
lxc-start: u-dns: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options

# Steps to reproduce

 1. Step one
lxc-start u-dns
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
```
May 29 09:56:43 zlebia kernel: [67433.181111] IPv6: ADDRCONF(NETDEV_UP): vethRQN33B: link is not ready
May 29 09:56:43 zlebia kernel: [67433.182047] lxcbr0: port 2(vethRQN33B) entered blocking state
May 29 09:56:43 zlebia kernel: [67433.182055] lxcbr0: port 2(vethRQN33B) entered disabled state
May 29 09:56:43 zlebia kernel: [67433.183540] device vethRQN33B entered promiscuous mode
May 29 09:56:43 zlebia kernel: [67433.208077] eth0: renamed from vethRQN33Bp
May 29 09:56:43 zlebia systemd-udevd[25765]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 29 09:56:43 zlebia systemd-udevd[25764]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 29 09:56:43 zlebia systemd-udevd[25764]: link_config: could not get ethtool features for vethRQN33Bp
May 29 09:56:43 zlebia systemd-udevd[25764]: Could not set offload features of vethRQN33Bp: No such device
May 29 09:56:43 zlebia kernel: [67433.860223] lxcbr0: port 2(vethRQN33B) entered disabled state
May 29 09:56:43 zlebia kernel: [67433.861316] device vethRQN33B left promiscuous mode
May 29 09:56:43 zlebia kernel: [67433.861340] lxcbr0: port 2(vethRQN33B) entered disabled state
```

 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)

```
lxc-start u-dns 20190528213551.156 INFO     confile - confile.c:set_config_idmaps:1555 - Read uid map: type u nsid 0 hostid 100000 range 65536
lxc-start u-dns 20190528213551.156 INFO     confile - confile.c:set_config_idmaps:1555 - Read uid map: type g nsid 0 hostid 100000 range 65536
lxc-start u-dns 20190528213551.157 INFO     lxccontainer - lxccontainer.c:do_lxcapi_start:961 - Set process title to [lxc monitor] /home/clem/.local/share/lxc u-dns
lxc-start u-dns 20190528213551.159 INFO     lsm - lsm/lsm.c:lsm_init:50 - LSM security driver AppArmor
lxc-start u-dns 20190528213551.159 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "reject_force_umount  # comment this to allow umount -f;  not recommended"
lxc-start u-dns 20190528213551.159 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start u-dns 20190528213551.159 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for reject_force_umount action 0(kill)
lxc-start u-dns 20190528213551.159 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start u-dns 20190528213551.159 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "[all]"
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "kexec_load errno 1"
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for kexec_load action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for kexec_load action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for kexec_load action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for kexec_load action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "open_by_handle_at errno 1"
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for open_by_handle_at action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for open_by_handle_at action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for open_by_handle_at action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for open_by_handle_at action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "init_module errno 1"
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for init_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for init_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for init_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for init_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "finit_module errno 1"
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for finit_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for finit_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for finit_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for finit_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "delete_module errno 1"
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for delete_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for delete_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for delete_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for delete_module action 327681(errno)
lxc-start u-dns 20190528213551.160 INFO     seccomp - seccomp.c:parse_config_v2:970 - Merging compat seccomp contexts into main context
lxc-start u-dns 20190528213551.162 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:707 - No such device - The process does not have a controlling terminal
lxc-start u-dns 20190528213551.163 DEBUG    conf - conf.c:chown_mapped_root:3166 - trying to chown "/dev/pts/7" to 1000
lxc-start u-dns 20190528213551.247 INFO     start - start.c:lxc_init:897 - Container "u-dns" is initialized
lxc-start u-dns 20190528213551.250 INFO     start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWUSER
lxc-start u-dns 20190528213551.250 INFO     start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWNS
lxc-start u-dns 20190528213551.250 INFO     start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWPID
lxc-start u-dns 20190528213551.250 INFO     start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWUTS
lxc-start u-dns 20190528213551.250 INFO     start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWIPC
lxc-start u-dns 20190528213551.251 DEBUG    start - start.c:lxc_try_preserve_namespaces:196 - Preserved user namespace via fd 14
lxc-start u-dns 20190528213551.251 DEBUG    start - start.c:lxc_try_preserve_namespaces:196 - Preserved mnt namespace via fd 15
lxc-start u-dns 20190528213551.251 DEBUG    start - start.c:lxc_try_preserve_namespaces:196 - Preserved pid namespace via fd 16
lxc-start u-dns 20190528213551.251 DEBUG    start - start.c:lxc_try_preserve_namespaces:196 - Preserved uts namespace via fd 17
lxc-start u-dns 20190528213551.251 DEBUG    start - start.c:lxc_try_preserve_namespaces:196 - Preserved ipc namespace via fd 18
lxc-start u-dns 20190528213551.251 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start u-dns 20190528213551.252 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start u-dns 20190528213551.252 DEBUG    conf - conf.c:lxc_map_ids:2928 - Functional newuidmap and newgidmap binary found
lxc-start u-dns 20190528213551.332 INFO     start - start.c:do_start:1136 - Unshared CLONE_NEWNET
lxc-start u-dns 20190528213551.334 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start u-dns 20190528213551.334 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start u-dns 20190528213551.335 DEBUG    conf - conf.c:lxc_map_ids:2928 - Functional newuidmap and newgidmap binary found
lxc-start u-dns 20190528213551.368 DEBUG    start - start.c:lxc_spawn:1742 - Preserved net namespace via fd 10
lxc-start u-dns 20190528213551.368 WARN     start - start.c:lxc_spawn:1746 - Operation not permitted - Failed to allocate new network namespace id
lxc-start u-dns 20190528213551.369 INFO     network - network.c:lxc_create_network_unpriv_exec:2150 - Execing lxc-user-nic create /home/clem/.local/share/lxc u-dns 27395 veth lxcbr0 (null)
lxc-start u-dns 20190528213551.433 NOTICE   utils - utils.c:lxc_switch_uid_gid:1378 - Switched to gid 0
lxc-start u-dns 20190528213551.433 NOTICE   utils - utils.c:lxc_switch_uid_gid:1387 - Switched to uid 0
lxc-start u-dns 20190528213551.433 NOTICE   utils - utils.c:lxc_setgroups:1400 - Dropped additional groups
lxc-start u-dns 20190528213551.434 INFO     start - start.c:do_start:1242 - Unshared CLONE_NEWCGROUP
lxc-start u-dns 20190528213551.446 ERROR    conf - conf.c:lxc_mount_rootfs:1317 - Failed to mount rootfs "/home/clem/.local/share/lxc/u-dns/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc" with options "(null)"
lxc-start u-dns 20190528213551.446 ERROR    conf - conf.c:lxc_setup_rootfs_prepare_root:3445 - Failed to setup rootfs for
lxc-start u-dns 20190528213551.446 ERROR    conf - conf.c:lxc_setup:3498 - Failed to setup rootfs
lxc-start u-dns 20190528213551.446 ERROR    start - start.c:do_start:1263 - Failed to setup container "u-dns"
lxc-start u-dns 20190528213551.447 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc-start u-dns 20190528213551.447 DEBUG    network - network.c:lxc_delete_network:3180 - Deleted network devices
lxc-start u-dns 20190528213551.448 DEBUG    lxccontainer - lxccontainer.c:wait_on_daemonized_start:830 - First child 27389 exited
lxc-start u-dns 20190528213551.448 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc-start u-dns 20190528213551.448 ERROR    lxc_start - tools/lxc_start.c:main:330 - The container failed to start
lxc-start u-dns 20190528213551.448 ERROR    lxc_start - tools/lxc_start.c:main:333 - To get more details, run the container in foreground mode
lxc-start u-dns 20190528213551.448 ERROR    lxc_start - tools/lxc_start.c:main:336 - Additional information can be obtained by setting the --logfile and --logpriority options
lxc-start u-dns 20190528213551.451 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "u-dns"
lxc-start u-dns 20190528213551.452 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start u-dns 20190528213551.453 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start u-dns 20190528213551.453 DEBUG    conf - conf.c:lxc_map_ids:2928 - Functional newuidmap and newgidmap binary found
lxc-start u-dns 20190528213551.489 INFO     conf - conf.c:run_script_argv:356 - Executing script "/usr/share/lxcfs/lxc.reboot.hook" for container "u-dns", config section "lxc"
lxc-start u-dns 20190528213902.112 ERROR    lxc_start - tools/lxc_start.c:main:290 - No container config specified
```

 - [ ] the containers configuration file
# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
lxc.rootfs.path = /home/clem/.local/share/lxc/u-dns/rootfs
lxc.uts.name = u-dns

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.ipv4.address = 10.0.3.147
lxc.net.0.hwaddr = c2:6f:aa:15:f3:91

**Comment by ClemLassAdeo** [comment]
Hello,
Is there some information missing in my ticket, so that it can be handled please ?
These unpriv containers worked without problem since years, on Ubuntu 16.04
Thank you for your help,
Best regards

**Comment by hallyn** [comment]
Is it possible to try with the https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxc-git-master  ppa?

**Comment by scritchplouf** [comment]
Hello,
Unfortunately the result is the same (please see logs attached)
[lxc-issue.txt](https://github.com/lxc/lxc/files/3395909/lxc-issue.txt)

Thank you for your help

**Comment by scritchplouf** [comment]
Precision : the unprivileged containers uses the following uid/gid mapping:
```
# grep clem /etc/sub*id
/etc/subgid:clem:100000:65537
/etc/subuid:clem:100000:65537
```
And the file permissions are set accordingly : 

```
# ls -ltr
drwxr-xr-x 21 100000 100000  4096 mai   11  2018 rootfs
-rw-rw-r--  1 clem   clem     708 mai   28 16:36 config
```

```
# ls -ltr rootfs/
total 76
drwxr-xr-x   2 100000 100000 4096 mars  13  2014 sys
drwxr-xr-x   2 100000 100000 4096 avril 11  2014 proc
drwxr-xr-x   2 100000 100000 4096 avril 11  2014 mnt
drwxr-xr-x   2 100000 100000 4096 avril 11  2014 boot
drwxr-xr-x  11 100000 100000 4096 janv. 12  2015 var
drwxr-xr-x  10 100000 100000 4096 janv. 12  2015 usr
drwxr-xr-x   2 100000 100000 4096 janv. 12  2015 srv
drwxr-xr-x   2 100000 100000 4096 janv. 12  2015 opt
drwxr-xr-x   2 100000 100000 4096 janv. 12  2015 media
drwxr-xr-x   8 100000 100000 4096 janv. 13  2015 run
drwxr-xr-x+  4 100000 100000 4096 janv. 13  2015 home
drwxr-xr-x  12 100000 100000 4096 août  20  2017 lib
drwxr-xr-x   2 100000 100000 4096 mars  12  2018 lib64
drwxr-xr-x   3 100000 100000 4096 mai   11  2018 dev
drwxr-xr-x   2 100000 100000 4096 juin  10  2018 sbin
drwxr-xr-x   2 100000 100000 4096 juin  10  2018 bin
drwxr-xr-x  73 100000 100000 4096 oct.  16  2018 etc
drwx------   2 100000 100000 4096 mars  12 08:36 root
drwxrwxrwt   2 100000 100000 4096 mai   28 08:23 tmp
```

So it does not look like the same problem as issue #3030
Thank you for your help.

**Comment by f-roscher** [comment]
I am having the same issue, but with a privileged container. All worked before dist-upgrading Debian to 'buster'.
I traced the error up to line 1340 of src/lxc/conf.c, being 'bdev = storage_init(conf);' returning false there. 
This is how far I got now. I'm trying to find out more, but would be glad for any hints.

**Comment by upmferraz** [comment]
Same issue here with Debian buster, any progress on this?

**Comment by Grundik** [comment]
I've traced this (or very similar) issue to rootfs type detection:
```
lxc-start u-dns 20190528213551.434 INFO start - start.c:do_start:1242 - Unshared CLONE_NEWCGROUP
***** there should be something like DEBUG    storage - storage/storage.c:storage_query:253 - Detected rootfs type "lvm" *****
lxc-start u-dns 20190528213551.446 ERROR conf - conf.c:lxc_mount_rootfs:1317 - Failed to mount rootfs "/home/clem/.local/share/lxc/u-dns/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc" with options "(null)"
```
So absence of this line means, that lxc was unable to detect storage type. Workaround could be to supply storage type manually:
`lxc.rootfs.path = lvm:/dev/....`

And then container starts like a charm.

**Comment by f-roscher** [comment]
I just came here to give my findings. Then I saw yours, @Grundik, thanks for that one. 
This matches my: I did use 'rbd' (raw block device - at least this is, what I think it does mean). 
So my line, for example, would be: `lxc.rootfs.path = rbd:/dev/drbd/by-disk/vgsys01/db01.root`

I did not dig deeper into differences between types lvm and rbd. I found rbd more appropriate for my case, having a DRBD device on top of an LVM LV. It might be LVM in the end, but because of DRBD I do not want any logic trying to tamper with it: Thus, just use it as an ordinary block device. 

So the issue might be LXC not detecting the type automatically because of the DRBD layer on top of it - my feature request would then be to traverse DRBD and find the underlying device. @Grundik, does something similar apply to your setup, too?

`root@hw01:~# blkid |grep db01.root
/dev/mapper/vgsys01-db01.root: UUID="be72a55e7c4c63cc" TYPE="drbd"
`

**Comment by Grundik** [comment]
In my case it was a dmcrypt luks device on top of LVM volume. LXC 3 cannot automatically determine such device type, but LXC 2 had no problems with that.

**Comment by jeremylowery** [comment]
I wanted to chime in on this to say that I'm having the same problem on Ubuntu after an upgrade from 14.04 to 16.04.  I'm running DRBD on top of LVM. If I mount the DRBD partition on the host and use lxc.rootfs = /var/lib/lxc/mycont/rootfs  it works fine. but giving lxc.rootfs = /dev/drbd5 is a no go.

As a test I copied the entire drbd partition to a new logical volume and used that as the rootfs = /dev/mvg/my-logical-volume.   This works correctly.

It definitely appears to be something with DRBD specifically.

I have many hosts running this setup on 14.04 Ubuntu and it works fine, so this is a regression. I kernel version is 4.4.0.  I also tried using the old kernel from before the upgrade 3.19.0 and no dice.
[log.txt](https://github.com/lxc/lxc/files/4175428/log.txt)

**Comment by jeremylowery** [comment]
After tracing back from lxc/storage/storage.c:storage_init , I have at least figured out a work around until this is fixed. If you prefix the path with loop: it works!

lxc.rootfs = loop:/dev/drbd5

Perhaps this has something to do with the automatic bdev_type calculation, but I haven't found that yet.

**Comment by f-roscher** [comment]
Adding a note to myself:
> [...] my feature request would then be to traverse DRBD and find the underlying device. @Grundik, does something similar apply to your setup, too?
On a second thought I do not think so. It might better to detect DRBD as a variant of a block device in itself, not look at what is below.

**Comment by stgraber** [comment]
@brauner anything we should do better in 4.0 to handle folks with `lxc.rootfs` pointing to a block device?

**Comment by brauner** [comment]
I think this is an upgrade issue essentially, since `lxc.rootfs.backend` was not translated correctly into the new config. This should now be fixed with `lxc-update-config` being able to handle the `lxc.rootfs.backend` key.

**Comment by scritchplouf** [comment]
Hello,
Sorry but unfortunately, for my setup the issue is not resolved : i use neither rbd nor lvm as backend, only a subdirectory for my rootfs, and the issue is still prevent with PPA / 3.2.1-devel, with the same error log than before...
Thanks for your help

**Comment by brauner** [comment]
> Hello,
> Sorry but unfortunately, for my setup the issue is not resolved : i use neither rbd nor lvm as backend, only a subdirectory for my rootfs, and the issue is still prevent with PPA / 3.2.1-devel, with the same error log than before...
> Thanks for your help

How does your config file look like?

**Comment by scritchplouf** [comment]
The config is :
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
lxc.rootfs.path = /home/clem/.local/share/lxc/u-dns/rootfs
lxc.uts.name = u-dns

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.ipv4.address = 10.0.3.147
lxc.net.0.hwaddr = c2:6f:aa:15:f3:91

**Comment by brauner** [comment]
Show the output of `findmnt`, please?

**Comment by scritchplouf** [comment]
Here it is :

TARGET                                SOURCE      FSTYPE      OPTIONS
/                                     /dev/sda2   ext4        rw,relatime,errors=remount-ro,data=ordered
├─/sys                                sysfs       sysfs       rw,relatime
│ ├─/sys/kernel/security              securityfs  securityfs  rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup                    tmpfs       tmpfs       ro,nosuid,nodev,noexec,mode=755
│ │ ├─/sys/fs/cgroup/unified          cgroup      cgroup2     rw,nosuid,nodev,noexec,relatime
│ │ ├─/sys/fs/cgroup/systemd          cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,xattr,name=systemd
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,cpu,cpuacct
│ │ ├─/sys/fs/cgroup/memory           cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,memory
│ │ ├─/sys/fs/cgroup/blkio            cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,blkio
│ │ ├─/sys/fs/cgroup/pids             cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,pids
│ │ ├─/sys/fs/cgroup/rdma             cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,rdma
│ │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,net_cls,net_prio
│ │ ├─/sys/fs/cgroup/perf_event       cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,perf_event
│ │ ├─/sys/fs/cgroup/freezer          cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,freezer
│ │ ├─/sys/fs/cgroup/devices          cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,devices
│ │ ├─/sys/fs/cgroup/cpuset           cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,cpuset,clone_children
│ │ └─/sys/fs/cgroup/hugetlb          cgroup      cgroup      rw,nosuid,nodev,noexec,relatime,hugetlb
│ ├─/sys/fs/pstore                    pstore      pstore      rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/debug                 debugfs     debugfs     rw,relatime
│ │ └─/sys/kernel/debug/tracing       tracefs     tracefs     rw,relatime
│ ├─/sys/kernel/config                configfs    configfs    rw,relatime
│ └─/sys/fs/fuse/connections          fusectl     fusectl     rw,relatime
├─/proc                               proc        proc        rw,relatime
│ └─/proc/sys/fs/binfmt_misc          systemd-1   autofs      rw,relatime,fd=34,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12083
│   └─/proc/sys/fs/binfmt_misc        binfmt_misc binfmt_misc rw,relatime
├─/dev                                udev        devtmpfs    rw,relatime,size=1980028k,nr_inodes=495007,mode=755
│ ├─/dev/pts                          devpts      devpts      rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
│ ├─/dev/shm                          tmpfs       tmpfs       rw,nosuid,nodev
│ ├─/dev/mqueue                       mqueue      mqueue      rw,relatime
│ └─/dev/hugepages                    hugetlbfs   hugetlbfs   rw,relatime,pagesize=2M
├─/run                                tmpfs       tmpfs       rw,nosuid,noexec,relatime,size=402200k,mode=755
│ ├─/run/lock                         tmpfs       tmpfs       rw,nosuid,nodev,noexec,relatime,size=5120k
│ └─/run/user/1000                    tmpfs       tmpfs       rw,nosuid,nodev,relatime,size=402196k,mode=700,uid=1000,gid=1000
├─/snap/core/8689                     /dev/loop1  squashfs    ro,nodev,relatime
├─/snap/hello-world/29                /dev/loop2  squashfs    ro,nodev,relatime
├─/home                               /dev/sda3   ext4        rw,relatime,data=ordered
├─/var/lib/lxcfs                      lxcfs       fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
├─/var/lib/lxd/shmounts               tmpfs       tmpfs       rw,relatime,size=100k,mode=711
├─/var/lib/lxd/devlxd                 tmpfs       tmpfs       rw,relatime,size=100k,mode=755
└─/snap/core/8592                     /dev/loop3  squashfs    ro,nodev,relatime

**Comment by brauner** [comment]
Can you please change
```
lxc.rootfs.path = /home/clem/.local/share/lxc/u-dns/rootfs
```
to
```
lxc.rootfs.path = dir:/home/clem/.local/share/lxc/u-dns/rootfs
```
please and try again?

**Comment by scritchplouf** [comment]
I now have a perm denied error :
`ERROR    dir - storage/dir.c:dir_mount:177 - Permission denied - Failed to mount "/home/clem/.local/share/lxc/u-dns/rootfs" on "/usr/lib/x86_64-linux-gnu/lxc"`

The uid on this directory (and subtree) are indeed uid and gid mapped :
`drwxr-xr-x 21 100000 100000 4096 mai   11  2018 u-dns/rootfs`

But subuid and subgid seems fine :

`$ cat /etc/subuid                                                                                                                                    
clem:100000:65537
$ cat /etc/subgid
clem:100000:65537`

**Comment by brauner** [comment]
What are the permissions on the target path `/usr/lib/x86_64-linux-gnu/lxc`?

**Comment by scritchplouf** [comment]
Here they are :
`drwxr-xr-x 3 root root 4096 févr. 10 10:11 /usr/lib/x86_64-linux-gnu/lxc`

**Comment by brauner** [comment]
Do you see any apparmor denials in your dmesg output?

**Comment by ClemLassAdeo** [comment]
No, I don't have any apparmor denials related to containers start... (no denials at all during the start "try & fail" operation)

**Comment by brauner** [comment]
So I've improved mounting for the rootfs a bit. Can you test with `4.0.3`?
