### ISSUE TITLE
lxc-stop in some Docker won't work

### ISSUE THREAD

**Issue by P-EB** [lxc/lxc#3471]
Hi,

Since we upgraded LXC to 4.0.2 in Debian unstable, the Debian Salsa CI seems to break out.

This post: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961584#22 contains a Dockerfile that allows to reproduce the issue. 

The trace obtained is:

```
Starting LXC network bridge: :Starting LXC autoboot containers: :
lxc-stop autopkgtest-stable-amd64 20200603085059.718 TRACE    commands - commands.c:lxc_cmd_rsp_recv:123 - Command "get_init_pid" received response
lxc-stop autopkgtest-stable-amd64 20200603085059.718 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:156 - Response data length for command "get_init_pid" is 0
lxc-stop autopkgtest-stable-amd64 20200603085059.718 TRACE    commands - commands.c:lxc_cmd:293 - Opened new command socket connection fd 4 for command "get_init_pid"
lxc-stop autopkgtest-stable-amd64 20200603085059.719 TRACE    commands - commands.c:lxc_cmd_rsp_recv:123 - Command "get_state" received response
lxc-stop autopkgtest-stable-amd64 20200603085059.719 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:156 - Response data length for command "get_state" is 0
lxc-stop autopkgtest-stable-amd64 20200603085059.719 TRACE    commands - commands.c:lxc_cmd:293 - Opened new command socket connection fd 4 for command "get_state"
lxc-stop autopkgtest-stable-amd64 20200603085059.719 DEBUG    commands - commands.c:lxc_cmd_get_state:656 - Container "autopkgtest-stable-amd64" is in "RUNNING" state
lxc-stop autopkgtest-stable-amd64 20200603085059.719 TRACE    commands - commands.c:lxc_cmd_rsp_recv:123 - Command "stop" received response
lxc-stop autopkgtest-stable-amd64 20200603085059.719 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:156 - Response data length for command "stop" is 0
lxc-stop autopkgtest-stable-amd64 20200603085059.719 TRACE    commands - commands.c:lxc_cmd:293 - Opened new command socket connection fd 4 for command "stop"
lxc-stop autopkgtest-stable-amd64 20200603085059.720 ERROR    commands - commands.c:lxc_cmd_stop:707 - No such file or directory - Failed to stop container "autopkgtest-stable-amd64"
lxc-stop: autopkgtest-stable-amd64: commands.c: lxc_cmd_stop: 707 No such file or directory - Failed to stop container "autopkgtest-stable-amd64"
```

I've dug a bit and here is what I was able to do, which wasn't enough to solve this:

In `commands.c`, at line 289, there is `ret = lxc_cmd_rsp_recv(client_fd, cmd)`;, and this return value is what triggers the error output line 707.

`lxc_cmd_rps_recv` probably returns with the `log_debug` call line 156, this return feeds the ret line 289. The ret in argument line 156 is filled from the output of `lxc_abstract_unix_recv_fds` call line 118. The ret being positive, I guess it’s the `recvmsg` call lline 192 of `af_unix.c` that returns a positive value where a 0 length response is expected for lxc-stop.

I wonder if the issue could lie in the fact that the lxc-stop is ran in a docker environment, and therefore a network permission could fail?

Could you either help me to dig deeper, or try it yourself and see if you manage to reproduce/understand?

Thanks!

**Comment by brauner** [comment]
Hm, we've released 4.0.4 and that should fix this issue, I think. Is there any chance you can upgrade to 4.0.4?

**Comment by P-EB** [comment]
@brauner sure, let's give it a try!

Could you tell me where you think the issue was lying?

**Comment by P-EB** [comment]
@brauner nope, doesn't work. :(

https://salsa.debian.org/ina/pipeline/-/jobs/990352 it's a pipeline ran with the new version of lxc and the issue still is here.

**Comment by P-EB** [comment]
(lxc 4.0.4 is the current release in Debian Unstable)

**Comment by P-EB** [comment]
@brauner the trace looks different:
```
Starting LXC network bridge: :Starting LXC autoboot containers: :lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_init_pid" received response
lxc-stop autopkgtest-stable-amd64 20200916205041.868 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_init_pid" is 0
lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_init_pid"
lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_state" received response
lxc-stop autopkgtest-stable-amd64 20200916205041.868 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_state"
lxc-stop autopkgtest-stable-amd64 20200916205041.868 DEBUG    commands - commands.c:lxc_cmd_get_state:724 - Container "autopkgtest-stable-amd64" is in "RUNNING" state
lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_state" received response
lxc-stop autopkgtest-stable-amd64 20200916205041.868 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_state"
lxc-stop autopkgtest-stable-amd64 20200916205041.868 DEBUG    commands - commands.c:lxc_cmd_get_state:724 - Container "autopkgtest-stable-amd64" is in "RUNNING" state
lxc-stop autopkgtest-stable-amd64 20200916205041.868 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_init_pidfd" received response
lxc-stop autopkgtest-stable-amd64 20200916205041.869 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_init_pidfd" is 0
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_init_pidfd"
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_init_pid" received response
lxc-stop autopkgtest-stable-amd64 20200916205041.869 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_init_pid" is 0
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_init_pid"
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "add_state_client" received response
lxc-stop autopkgtest-stable-amd64 20200916205041.869 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "add_state_client" is 0
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "add_state_client"
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    commands - commands.c:lxc_cmd_add_state_client:1036 - State connection fd 4 ready to listen for container state changes
lxc-stop autopkgtest-stable-amd64 20200916205041.869 TRACE    lxccontainer - lxccontainer.c:do_lxcapi_shutdown:2107 - Sent signal 30 to pidfd 5
lxc-stop: autopkgtest-stable-amd64: commands.c: lxc_cmd_stop: 775 No such file or directory - Failed to stop container "autopkgtest-stable-amd64"
lxc-stop autopkgtest-stable-amd64 20200916205141.927 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "stop" received response
lxc-stop autopkgtest-stable-amd64 20200916205141.927 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "stop" is 0
lxc-stop autopkgtest-stable-amd64 20200916205141.927 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "stop"
lxc-stop autopkgtest-stable-amd64 20200916205141.927 ERROR    commands - commands.c:lxc_cmd_stop:775 - No such file or directory - Failed to stop container "autopkgtest-stable-amd64"
```

Hope this helps.

**Comment by P-EB** [comment]
I can try running some more tests if needed.

**Comment by P-EB** [comment]
Uh. I did a stupid trial: the test used for this experimentation is from a Dockerfile that runs lxc-start autopkgtest-stable-amd64 && lxc-stop autopkgtest-stable-amd64 . I wondered if that issue about stopping the container wasn't due to the fact the stop is launched before the container has finished being started and therefore not in a good state to take api calls.

Turns out, adding a sleep 1 or sleep 2 between the start and the stop makes the issue vanish…

Isn't there a way in your scope to have a lxc-stop called too soon to retry sending the signal or check the current state of the container before sending the signal?

**Comment by brauner** [comment]
Hm, I think I understand where this issue comes from and I think it's caused by the freezer controller not being used or available for this container which causes us to incorrectly report `ENOENT` back to `lxc_cmd_stop()`. This needs fixing but to confirm whether that is really your issue too, could you please provide me with two logs:

```
lxc-start <bla> -l trace -o <bla>.start.log
lxc-stop <bla> -l trace -o <bla>.stop.log
```

I need to see both logs because I some messages are logged to `<bla>.start.log` during `lxc-stop`.

**Comment by P-EB** [comment]
@brauner will try to do that this evening.

In the meantime, Antonio Terceiro did a bit more debugging, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961584#69

It seems that the kill flag is at cause here. There are some straces output. I'll try to complete with a proper log.

**Comment by P-EB** [comment]
@brauner 

lxc_start.log
```
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    commands - commands.c:lxc_cmd:289 - Connection refused - Command "get_init_pid" failed to connect command socket
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    commands - commands.c:lxc_cmd:289 - Connection refused - Command "get_state" failed to connect command socket
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init_handler:692 - Created anonymous pair {4,5} of unix sockets
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    commands - commands.c:lxc_cmd_init:1671 - Created abstract unix socket "/lxc/autopkgtest-stable-amd64/command"
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init_handler:708 - Unix domain socket 6 for command server is ready
lxc-start autopkgtest-stable-amd64 20200917145033.306 INFO     lxccontainer - lxccontainer.c:do_lxcapi_start:969 - Set process title to [lxc monitor] /lxc autopkgtest-stable-amd64
lxc-start autopkgtest-stable-amd64 20200917145033.306 DEBUG    lxccontainer - lxccontainer.c:wait_on_daemonized_start:830 - First child 52 exited
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_start:2113 - Doing lxc_start
lxc-start autopkgtest-stable-amd64 20200917145033.306 INFO     lsm - lsm/lsm.c:lsm_init:30 - LSM security driver AppArmor
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init:732 - Initialized LSM
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_serve_state_clients:438 - Set container state to STARTING
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_serve_state_clients:441 - No state clients registered
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init:738 - Set container state to "STARTING"
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init:794 - Set environment variables
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init:799 - Ran pre-start hooks
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:setup_signal_fd:331 - Created signal file descriptor 8
lxc-start autopkgtest-stable-amd64 20200917145033.306 TRACE    start - start.c:lxc_init:808 - Set up signal fd
lxc-start autopkgtest-stable-amd64 20200917145033.307 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:655 - No such device - The process does not have a controlling terminal
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    start - start.c:lxc_init:816 - Created console
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    start - start.c:lxc_init:823 - Chowned console
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:941 - basecginfo is:
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:942 - 11:freezer:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
10:cpuset:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
9:perf_event:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
8:devices:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
7:blkio:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
6:rdma:/
5:pids:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
4:cpu,cpuacct:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
3:net_cls,net_prio:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
2:memory:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
1:name=systemd:/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
0::/system.slice/docker.service

lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 0: freezer
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 1: cpuset
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 2: perf_event
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 3: devices
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 4: blkio
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 5: rdma
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 6: pids
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 7: cpu
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 8: cpuacct
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 9: net_cls
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 10: net_prio
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 11: memory
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:945 - kernel subsystem 12: cgroup2
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_basecg_debuginfo:948 - named subsystem 0: name=systemd
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:cg_hybrid_init:3279 - Writable cgroup hierarchies:
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:922 -   Hierarchies:
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:927 -   0: base_cgroup: /docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:928 -       mountpoint:  /sys/fs/cgroup/cpuset
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:929 -       controllers:
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:931 -       0: cpuset
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:927 -   1: base_cgroup: /docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:928 -       mountpoint:  /sys/fs/cgroup/devices
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:929 -       controllers:
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgfsng - cgroups/cgfsng.c:lxc_cgfsng_print_hierarchies:931 -       0: devices
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgroup - cgroups/cgroup.c:cgroup_init:41 - Initialized cgroup driver cgfsng
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    cgroup - cgroups/cgroup.c:cgroup_init:44 - Running with legacy cgroup layout
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    start - start.c:lxc_init:830 - Initialized cgroup driver
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:get_new_ctx:470 - Added arch 2 to main seccomp context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:get_new_ctx:478 - Removed native arch from main seccomp context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:get_new_ctx:470 - Added arch 3 to main seccomp context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:get_new_ctx:478 - Removed native arch from main seccomp context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:get_new_ctx:483 - Arch 4 already present in main seccomp context
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "reject_force_umount  # comment this to allow umount -f;  not recommended"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:do_resolve_add_rule:517 - Set seccomp rule to reject force umounts
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:985 - Added native rule for arch 0 for reject_force_umount action 0(kill)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:do_resolve_add_rule:517 - Set seccomp rule to reject force umounts
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:do_resolve_add_rule:517 - Set seccomp rule to reject force umounts
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:do_resolve_add_rule:517 - Set seccomp rule to reject force umounts
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1014 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "[all]"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "kexec_load errno 1"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:985 - Added native rule for arch 0 for kexec_load action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741827 for kexec_load action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added compat rule for arch 1073741886 for kexec_load action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1014 - Added native rule for arch -1073741762 for kexec_load action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "open_by_handle_at errno 1"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:985 - Added native rule for arch 0 for open_by_handle_at action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741827 for open_by_handle_at action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added compat rule for arch 1073741886 for open_by_handle_at action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1014 - Added native rule for arch -1073741762 for open_by_handle_at action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "init_module errno 1"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:985 - Added native rule for arch 0 for init_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741827 for init_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added compat rule for arch 1073741886 for init_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1014 - Added native rule for arch -1073741762 for init_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "finit_module errno 1"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:985 - Added native rule for arch 0 for finit_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741827 for finit_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added compat rule for arch 1073741886 for finit_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1014 - Added native rule for arch -1073741762 for finit_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:790 - Processing "delete_module errno 1"
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:985 - Added native rule for arch 0 for delete_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741827 for delete_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added compat rule for arch 1073741886 for delete_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1014 - Added native rule for arch -1073741762 for delete_module action 327681(errno)
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     seccomp - seccomp.c:parse_config_v2:1020 - Merging compat seccomp contexts into main context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:parse_config_v2:1030 - Merged first compat seccomp context into main context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    seccomp - seccomp.c:parse_config_v2:1046 - Merged second compat seccomp context into main context
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    start - start.c:lxc_init:835 - Read seccomp policy
lxc-start autopkgtest-stable-amd64 20200917145033.307 TRACE    start - start.c:lxc_init:842 - Initialized LSM
lxc-start autopkgtest-stable-amd64 20200917145033.307 INFO     start - start.c:lxc_init:844 - Container "autopkgtest-stable-amd64" is initialized
lxc-start autopkgtest-stable-amd64 20200917145033.329 TRACE    cgfsng - cgroups/cgfsng.c:cg_legacy_handle_cpuset_hierarchy:552 - "cgroup.clone_children" was already set to "1"
lxc-start autopkgtest-stable-amd64 20200917145033.329 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11/lxc.monitor.autopkgtest-stable-amd64"
lxc-start autopkgtest-stable-amd64 20200917145033.329 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1368 - The monitor process uses "lxc.monitor.autopkgtest-stable-amd64" as cgroup
lxc-start autopkgtest-stable-amd64 20200917145033.329 TRACE    cgfsng - cgroups/cgfsng.c:cg_legacy_handle_cpuset_hierarchy:552 - "cgroup.clone_children" was already set to "1"
lxc-start autopkgtest-stable-amd64 20200917145033.329 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset/docker/e9bfbc081a0eafb2dac3fb958c039b15ec214440fcacdea421a38bd350a04e11/lxc.payload.autopkgtest-stable-amd64"
lxc-start autopkgtest-stable-amd64 20200917145033.329 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1471 - The container process uses "lxc.payload.autopkgtest-stable-amd64" as cgroup
lxc-start autopkgtest-stable-amd64 20200917145033.330 TRACE    start - start.c:lxc_spawn:1690 - Cloned child process 54
lxc-start autopkgtest-stable-amd64 20200917145033.330 TRACE    utils - utils.c:lxc_can_use_pidfd:1861 - Kernel supports pidfds
lxc-start autopkgtest-stable-amd64 20200917145033.331 INFO     start - start.c:lxc_spawn:1706 - Cloned CLONE_NEWNS
lxc-start autopkgtest-stable-amd64 20200917145033.331 INFO     start - start.c:lxc_spawn:1706 - Cloned CLONE_NEWPID
lxc-start autopkgtest-stable-amd64 20200917145033.331 INFO     start - start.c:lxc_spawn:1706 - Cloned CLONE_NEWUTS
lxc-start autopkgtest-stable-amd64 20200917145033.331 INFO     start - start.c:lxc_spawn:1706 - Cloned CLONE_NEWIPC
lxc-start autopkgtest-stable-amd64 20200917145033.331 INFO     start - start.c:lxc_spawn:1706 - Cloned CLONE_NEWNET
lxc-start autopkgtest-stable-amd64 20200917145033.331 DEBUG    start - start.c:lxc_try_preserve_namespaces:166 - Preserved mnt namespace via fd 19
lxc-start autopkgtest-stable-amd64 20200917145033.331 DEBUG    start - start.c:lxc_try_preserve_namespaces:166 - Preserved pid namespace via fd 20
lxc-start autopkgtest-stable-amd64 20200917145033.331 DEBUG    start - start.c:lxc_try_preserve_namespaces:166 - Preserved uts namespace via fd 21
lxc-start autopkgtest-stable-amd64 20200917145033.331 DEBUG    start - start.c:lxc_try_preserve_namespaces:166 - Preserved ipc namespace via fd 22
lxc-start autopkgtest-stable-amd64 20200917145033.331 DEBUG    start - start.c:lxc_try_preserve_namespaces:166 - Preserved net namespace via fd 23
lxc-start autopkgtest-stable-amd64 20200917145033.331 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2865 - Limits for the legacy cgroup hierarchies have been setup
lxc-start autopkgtest-stable-amd64 20200917145033.331 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:2926 - Invalid argument - Ignoring cgroup2 limits on legacy cgroup system
lxc-start autopkgtest-stable-amd64 20200917145033.331 TRACE    start - start.c:lxc_spawn:1786 - Allocated new network namespace id
lxc-start autopkgtest-stable-amd64 20200917145033.339 INFO     network - network.c:instantiate_veth:285 - Retrieved mtu 1500 from lxcbr0
lxc-start autopkgtest-stable-amd64 20200917145033.339 INFO     network - network.c:instantiate_veth:333 - Attached "vethUSiQ1e" to bridge "lxcbr0"
lxc-start autopkgtest-stable-amd64 20200917145033.339 DEBUG    network - network.c:instantiate_veth:449 - Instantiated veth tunnel "vethUSiQ1e <--> vethmVMOmq"
lxc-start autopkgtest-stable-amd64 20200917145033.339 TRACE    network - network.c:lxc_network_send_to_child:3558 - Sent network device name "vethmVMOmq" to child
lxc-start autopkgtest-stable-amd64 20200917145033.339 TRACE    network - network.c:lxc_network_recv_from_parent:3585 - Received network device name "vethmVMOmq" from parent
lxc-start autopkgtest-stable-amd64 20200917145033.339 INFO     start - start.c:do_start:1204 - Unshared CLONE_NEWCGROUP
lxc-start autopkgtest-stable-amd64 20200917145033.340 TRACE    conf - conf.c:turn_into_dependent_mounts:3010 - Turned all mount table entries into dependent mount
lxc-start autopkgtest-stable-amd64 20200917145033.340 DEBUG    storage - storage/storage.c:get_storage_by_name:211 - Detected rootfs type "dir"
lxc-start autopkgtest-stable-amd64 20200917145033.340 TRACE    dir - storage/dir.c:dir_mount:165 - Mounted "/lxc/autopkgtest-stable-amd64/rootfs" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs" with options "(null)", mount flags "0", and propagation flags "0"
lxc-start autopkgtest-stable-amd64 20200917145033.340 DEBUG    conf - conf.c:lxc_mount_rootfs:1259 - Mounted rootfs "/lxc/autopkgtest-stable-amd64/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs" with options "(null)"
lxc-start autopkgtest-stable-amd64 20200917145033.340 INFO     conf - conf.c:setup_utsname:752 - Set hostname to "autopkgtest-stable-amd64"
lxc-start autopkgtest-stable-amd64 20200917145033.369 TRACE    network - network.c:__instantiate_ns_common:884 - Renamed network device from "vethmVMOmq" to "eth%d"
lxc-start autopkgtest-stable-amd64 20200917145033.369 DEBUG    network - network.c:setup_hw_addr:3360 - Mac address "00:16:3e:15:18:87" on "eth0" has been setup
lxc-start autopkgtest-stable-amd64 20200917145033.369 DEBUG    network - network.c:lxc_network_setup_in_child_namespaces_common:3510 - Network device "eth0" has been setup
lxc-start autopkgtest-stable-amd64 20200917145033.369 INFO     network - network.c:lxc_setup_network_in_child_namespaces:3532 - Network has been setup
lxc-start autopkgtest-stable-amd64 20200917145033.369 TRACE    network - network.c:lxc_network_send_name_and_ifindex_to_parent:3618 - Sent network device names and ifindices to parent
lxc-start autopkgtest-stable-amd64 20200917145033.369 TRACE    conf - conf.c:lxc_setup:3232 - Created detached mount for container's console "/dev/pts/0"
lxc-start autopkgtest-stable-amd64 20200917145033.369 INFO     conf - conf.c:mount_autodev:1060 - Preparing "/dev"
lxc-start autopkgtest-stable-amd64 20200917145033.369 DEBUG    conf - conf.c:mount_autodev:1066 - Using mount options: size=500000,mode=755
lxc-start autopkgtest-stable-amd64 20200917145033.369 TRACE    conf - conf.c:mount_autodev:1086 - Mounted tmpfs on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev"
lxc-start autopkgtest-stable-amd64 20200917145033.369 INFO     conf - conf.c:mount_autodev:1109 - Prepared "/dev"
lxc-start autopkgtest-stable-amd64 20200917145033.370 DEBUG    conf - conf.c:mount_entry:1898 - Remounting "/sys/fs/fuse/connections" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/sys/fs/fuse/connections" to respect bind or remount options
lxc-start autopkgtest-stable-amd64 20200917145033.370 DEBUG    conf - conf.c:mount_entry:1917 - Flags for "/sys/fs/fuse/connections" were 4110, required extra flags are 14
lxc-start autopkgtest-stable-amd64 20200917145033.370 DEBUG    conf - conf.c:mount_entry:1961 - Mounted "/sys/fs/fuse/connections" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/sys/fs/fuse/connections" with filesystem type "none"
lxc-start autopkgtest-stable-amd64 20200917145033.370 INFO     conf - conf.c:run_script_argv:340 - Executing script "/usr/share/lxcfs/lxc.mount.hook" for container "autopkgtest-stable-amd64", config section "lxc"
lxc-start autopkgtest-stable-amd64 20200917145033.373 INFO     conf - conf.c:lxc_fill_autodev:1153 - Populating "/dev"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_fill_autodev:1168 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/full"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_fill_autodev:1168 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/null"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_fill_autodev:1168 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/random"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_fill_autodev:1168 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/tty"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_fill_autodev:1168 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/urandom"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_fill_autodev:1168 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/zero"
lxc-start autopkgtest-stable-amd64 20200917145033.373 INFO     conf - conf.c:lxc_fill_autodev:1223 - Populated "/dev"
lxc-start autopkgtest-stable-amd64 20200917145033.373 INFO     utils - utils.c:lxc_mount_proc_if_needed:1200 - I am 1, /proc/self points to "1"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_setup_dev_console:1626 - Moved mount "/dev/pts/0" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/console"
lxc-start autopkgtest-stable-amd64 20200917145033.373 DEBUG    conf - conf.c:lxc_setup_dev_console:1641 - Mounted pty device 17(/dev/pts/0) onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/console"
lxc-start autopkgtest-stable-amd64 20200917145033.374 TRACE    conf - conf.c:lxc_pivot_root:1428 - pivot_root("/usr/lib/x86_64-linux-gnu/lxc/rootfs") successful
lxc-start autopkgtest-stable-amd64 20200917145033.374 ERROR    conf - conf.c:lxc_setup_boot_id:3165 - Permission denied - Failed to mount /dev/.lxc-boot-id to /proc/sys/kernel/random/boot_id
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_setup_devpts:1522 - Mount new devpts instance with options "gid=5,newinstance,ptmxmode=0666,mode=0620,max=1024"
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_setup_devpts:1537 - Created dummy "/dev/ptmx" file as bind mount target
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_setup_devpts:1542 - Bind mounted "/dev/pts/ptmx" to "/dev/ptmx"
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_allocate_ttys:939 - Created tty "/dev/pts/0" with ptx fd 18 and pty fd 19
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_allocate_ttys:939 - Created tty "/dev/pts/1" with ptx fd 20 and pty fd 21
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_allocate_ttys:939 - Created tty "/dev/pts/2" with ptx fd 22 and pty fd 23
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_allocate_ttys:939 - Created tty "/dev/pts/3" with ptx fd 24 and pty fd 25
lxc-start autopkgtest-stable-amd64 20200917145033.374 INFO     conf - conf.c:lxc_allocate_ttys:956 - Finished creating 4 tty devices
lxc-start autopkgtest-stable-amd64 20200917145033.374 TRACE    conf - conf.c:lxc_send_ttys_to_parent:997 - Sent tty "/dev/pts/0" with ptx fd 18 and pty fd 19 to parent
lxc-start autopkgtest-stable-amd64 20200917145033.374 TRACE    conf - conf.c:lxc_send_ttys_to_parent:997 - Sent tty "/dev/pts/1" with ptx fd 20 and pty fd 21 to parent
lxc-start autopkgtest-stable-amd64 20200917145033.374 TRACE    conf - conf.c:lxc_send_ttys_to_parent:997 - Sent tty "/dev/pts/2" with ptx fd 22 and pty fd 23 to parent
lxc-start autopkgtest-stable-amd64 20200917145033.374 TRACE    conf - conf.c:lxc_send_ttys_to_parent:997 - Sent tty "/dev/pts/3" with ptx fd 24 and pty fd 25 to parent
lxc-start autopkgtest-stable-amd64 20200917145033.374 TRACE    conf - conf.c:lxc_send_ttys_to_parent:1004 - Sent 4 ttys to parent
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_setup_ttys:894 - Bind mounted "/dev/pts/0" onto "/dev/tty1"
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_setup_ttys:894 - Bind mounted "/dev/pts/1" onto "/dev/tty2"
lxc-start autopkgtest-stable-amd64 20200917145033.374 DEBUG    conf - conf.c:lxc_setup_ttys:894 - Bind mounted "/dev/pts/2" onto "/dev/tty3"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:lxc_setup_ttys:894 - Bind mounted "/dev/pts/3" onto "/dev/tty4"
lxc-start autopkgtest-stable-amd64 20200917145033.375 INFO     conf - conf.c:lxc_setup_ttys:901 - Finished setting up 4 /dev/tty<N> device(s)
lxc-start autopkgtest-stable-amd64 20200917145033.375 INFO     conf - conf.c:setup_personality:1573 - Set personality to "0x0"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:setup_caps:2373 - Dropped mac_admin (33) capability
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:setup_caps:2373 - Dropped mac_override (32) capability
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:setup_caps:2373 - Dropped sys_time (25) capability
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:setup_caps:2373 - Dropped sys_module (16) capability
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:setup_caps:2373 - Dropped sys_rawio (17) capability
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    conf - conf.c:setup_caps:2376 - Capabilities have been setup
lxc-start autopkgtest-stable-amd64 20200917145033.375 NOTICE   conf - conf.c:lxc_setup:3361 - The container "autopkgtest-stable-amd64" is set up
lxc-start autopkgtest-stable-amd64 20200917145033.375 INFO     lsm - lsm/lsm.c:lsm_process_label_set_at:158 - Set AppArmor label to "unconfined"
lxc-start autopkgtest-stable-amd64 20200917145033.375 INFO     apparmor - lsm/apparmor.c:apparmor_process_label_set:1185 - Changed AppArmor profile to unconfined
#
# pseudo filter code start
#
# filter for arch x86_64 (3221225534)
if ($arch == 3221225534)
  # filter for syscall "finit_module" (313) [priority: 65535]
  if ($syscall == 313)
    action ERRNO(1);
  # filter for syscall "open_by_handle_at" (304) [priority: 65535]
  if ($syscall == 304)
    action ERRNO(1);
  # filter for syscall "kexec_load" (246) [priority: 65535]
  if ($syscall == 246)
    action ERRNO(1);
  # filter for syscall "delete_module" (176) [priority: 65535]
  if ($syscall == 176)
    action ERRNO(1);
  # filter for syscall "init_module" (175) [priority: 65535]
  if ($syscall == 175)
    action ERRNO(1);
  # filter for syscall "umount2" (166) [priority: 65533]
  if ($syscall == 166)
    if ($a1.hi32 & 0x00000000 == 0)
      if ($a1.lo32 & 0x00000001 == 1)
        action ERRNO(13);
  # default action
  action ALLOW;
# filter for arch x86 (1073741827)
if ($arch == 1073741827)
  # filter for syscall "finit_module" (350) [priority: 65535]
  if ($syscall == 350)
    action ERRNO(1);
  # filter for syscall "open_by_handle_at" (342) [priority: 65535]
  if ($syscall == 342)
    action ERRNO(1);
  # filter for syscall "kexec_load" (283) [priority: 65535]
  if ($syscall == 283)
    action ERRNO(1);
  # filter for syscall "delete_module" (129) [priority: 65535]
  if ($syscall == 129)
    action ERRNO(1);
  # filter for syscall "init_module" (128) [priority: 65535]
  if ($syscall == 128)
    action ERRNO(1);
  # filter for syscall "umount2" (52) [priority: 65534]
  if ($syscall == 52)
    if ($a1 & 0x00000001 == 1)
      action ERRNO(13);
  # default action
  action ALLOW;
# filter for arch x32 (3221225534)
if ($arch == 3221225534)
  # filter for syscall "kexec_load" (1073742352) [priority: 65535]
  if ($syscall == 1073742352)
    action ERRNO(1);
  # filter for syscall "finit_module" (1073742137) [priority: 65535]
  if ($syscall == 1073742137)
    action ERRNO(1);
  # filter for syscall "open_by_handle_at" (1073742128) [priority: 65535]
  if ($syscall == 1073742128)
    action ERRNO(1);
  # filter for syscall "delete_module" (1073742000) [priority: 65535]
  if ($syscall == 1073742000)
    action ERRNO(1);
  # filter for syscall "init_module" (1073741999) [priority: 65535]
  if ($syscall == 1073741999)
    action ERRNO(1);
  # filter for syscall "umount2" (1073741990) [priority: 65534]
  if ($syscall == 1073741990)
    if ($a1 & 0x00000001 == 1)
      action ERRNO(13);
  # default action
  action ALLOW;
# invalid architecture action
action KILL;
#
# pseudo filter code end
#
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.deny" set to "a"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c *:* m"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "b *:* m"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 1:3 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 1:5 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 1:7 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 5:0 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 5:1 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 5:2 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 1:8 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 1:9 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 136:* rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.375 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 10:229 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.376 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 254:0 rm"
lxc-start autopkgtest-stable-amd64 20200917145033.376 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 10:200 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.376 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 10:228 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.376 DEBUG    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2860 - Set controller "devices.allow" set to "c 10:232 rwm"
lxc-start autopkgtest-stable-amd64 20200917145033.376 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2865 - Limits for the legacy cgroup hierarchies have been setup
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_spawn:1837 - Set up legacy device cgroup controller limits
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_spawn:1843 - Set up cgroup2 device controller limits
lxc-start autopkgtest-stable-amd64 20200917145033.376 DEBUG    start - start.c:lxc_spawn:1855 - Preserved cgroup namespace via fd 7
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_spawn:1860 - Finished setting up cgroups
lxc-start autopkgtest-stable-amd64 20200917145033.376 NOTICE   utils - utils.c:lxc_setgroups:1366 - Dropped additional groups
lxc-start autopkgtest-stable-amd64 20200917145033.376 NOTICE   start - start.c:start:2086 - Exec'ing "/sbin/init"
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:254 - index: 0
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:255 - ifindex: 2
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:259 - type: veth
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:266 - veth1 : vethUSiQ1e
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:270 - host side ifindex for veth device: 3
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:319 - flags: up
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:323 - link: lxcbr0
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:327 - l2proxy: false
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:330 - name: eth0
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:333 - hwaddr: 00:16:3e:15:18:87
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:344 - ipv4 gateway auto: false
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:347 - ipv4 gateway dev: false
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:363 - ipv6 gateway auto: false
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    confile_utils - confile_utils.c:lxc_log_configured_netdevs:366 - ipv6 gateway dev: false
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_recv_ttys_from_child:1440 - Received pty with ptx fd 11 and pty fd 15 from child
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_recv_ttys_from_child:1440 - Received pty with ptx fd 16 and pty fd 24 from child
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_recv_ttys_from_child:1440 - Received pty with ptx fd 25 and pty fd 26 from child
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_recv_ttys_from_child:1440 - Received pty with ptx fd 27 and pty fd 28 from child
lxc-start autopkgtest-stable-amd64 20200917145033.376 TRACE    start - start.c:lxc_recv_ttys_from_child:1446 - Received 4 ttys from child
lxc-start autopkgtest-stable-amd64 20200917145033.376 NOTICE   start - start.c:post_start:2097 - Started "/sbin/init" with pid "54"
lxc-start autopkgtest-stable-amd64 20200917145033.377 TRACE    start - start.c:lxc_serve_state_socket_pair:502 - Sent container state "RUNNING" to 5
lxc-start autopkgtest-stable-amd64 20200917145033.377 TRACE    start - start.c:lxc_serve_state_clients:438 - Set container state to RUNNING
lxc-start autopkgtest-stable-amd64 20200917145033.377 TRACE    start - start.c:lxc_serve_state_clients:441 - No state clients registered
lxc-start autopkgtest-stable-amd64 20200917145033.377 TRACE    lxccontainer - lxccontainer.c:wait_on_daemonized_start:854 - Container is in "RUNNING" state
lxc-start autopkgtest-stable-amd64 20200917145033.377 TRACE    start - start.c:lxc_poll:592 - Mainloop is ready
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "get_init_pid"
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "get_state"
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "get_state"
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "get_init_pidfd"
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "get_init_pid"
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145033.383 TRACE    commands_utils - commands_utils.c:lxc_add_state_client:191 - Added state client fd 12 to state client list
lxc-start autopkgtest-stable-amd64 20200917145133.443 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1543 - Found state client fd 12 in state client list for command "add_state_client"
lxc-start autopkgtest-stable-amd64 20200917145133.443 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1553 - Closing state client fd 12 for command "add_state_client"
lxc-start autopkgtest-stable-amd64 20200917145133.443 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "add_state_client"
lxc-start autopkgtest-stable-amd64 20200917145133.443 TRACE    commands - commands.c:lxc_cmd_accept:1644 - Accepted new client as fd 12 on command server fd 6
lxc-start autopkgtest-stable-amd64 20200917145133.443 TRACE    commands - commands.c:lxc_cmd_stop_callback:799 - Sent signal 9 to pidfd 18
lxc-start autopkgtest-stable-amd64 20200917145133.443 WARN     cgfsng - cgroups/cgfsng.c:get_hierarchy:172 - There is no useable freezer controller
lxc-start autopkgtest-stable-amd64 20200917145133.443 ERROR    commands - commands.c:lxc_cmd_stop_callback:807 - Failed to unfreeze container "autopkgtest-stable-amd64"
lxc-start autopkgtest-stable-amd64 20200917145133.444 TRACE    commands - commands.c:lxc_cmd_fd_cleanup:1556 - Closing client fd 12 for command "stop"
```

lxc_stop.log
```
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_init_pid" received response
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_init_pid" is 0
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_init_pid"
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_state" received response
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_state"
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_get_state:724 - Container "autopkgtest-stable-amd64" is in "RUNNING" state
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_state" received response
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_state"
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_get_state:724 - Container "autopkgtest-stable-amd64" is in "RUNNING" state
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_init_pidfd" received response
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_init_pidfd" is 0
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_init_pidfd"
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "get_init_pid" received response
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_init_pid" is 0
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "get_init_pid"
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "add_state_client" received response
lxc-stop autopkgtest-stable-amd64 20200917145033.383 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "add_state_client" is 0
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "add_state_client"
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    commands - commands.c:lxc_cmd_add_state_client:1036 - State connection fd 4 ready to listen for container state changes
lxc-stop autopkgtest-stable-amd64 20200917145033.383 TRACE    lxccontainer - lxccontainer.c:do_lxcapi_shutdown:2107 - Sent signal 30 to pidfd 5
lxc-stop autopkgtest-stable-amd64 20200917145133.443 TRACE    commands - commands.c:lxc_cmd_rsp_recv:125 - Command "stop" received response
lxc-stop autopkgtest-stable-amd64 20200917145133.444 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "stop" is 0
lxc-stop autopkgtest-stable-amd64 20200917145133.444 TRACE    commands - commands.c:lxc_cmd:297 - Opened new command socket connection fd 4 for command "stop"
lxc-stop autopkgtest-stable-amd64 20200917145133.444 ERROR    commands - commands.c:lxc_cmd_stop:775 - No such file or directory - Failed to stop container "autopkgtest-stable-amd64"
```
