### ISSUE TITLE
lxc-attach: nginx-debian: lsm/lsm.c: lsm_process_label_set_at: 174 Operation not permitted - Failed to set AppArmor label "lxc-nginx-debian_</var/lib/lxc>//&:lxc-nginx-debian_<-var-lib-lxc>:unconfined"

### ISSUE THREAD

**Issue by Sina-Ghaderi** [lxc/lxc#3872]
# Required information

 * `Debain buster kernel Linux debian-lxc 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux`
 
   * `lxc-start --version --> 3.0.3`
   * `lxc-checkconfig`
 ```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.19.0-17-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/rdma
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```
   * `cat /proc/self/cgroup`
 ```
11:memory:/system.slice/ssh.service
10:pids:/system.slice/ssh.service
9:cpuset:/
8:blkio:/system.slice/ssh.service
7:net_cls,net_prio:/
6:perf_event:/
5:cpu,cpuacct:/system.slice/ssh.service
4:rdma:/
3:freezer:/
2:devices:/system.slice/ssh.service
1:name=systemd:/system.slice/ssh.service
0::/system.slice/ssh.service

```
   * `cat /proc/1/mounts`
```
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=3037876k,nr_inodes=759469,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=610552k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=9619 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
/dev/loop0 /var/lib/lxc/nginx-debian/rootfs/var/www/hihesab.ir ext4 rw,relatime 0 0
/dev/loop1 /var/lib/lxc/nginx-debian/rootfs/var/www/macit.ir ext4 rw,relatime 0 0
/dev/loop2 /var/lib/lxc/nginx-debian/rootfs/var/www/zerocam.ir ext4 rw,relatime 0 0

```
# Issue description
Error in attaching lxc container with `lxc-attach -n nginx-debian`  after upgrading debian kernel to 4.19.0-17-amd64
```
lxc-attach: nginx-debian: lsm/lsm.c: lsm_process_label_set_at: 174 Operation not permitted - Failed to set AppArmor label "lxc-nginx-debian_</var/lib/lxc>//&:lxc-nginx-debian_<-var-lib-lxc>:unconfined"
```

**Comment by lanmarc77** [comment]
This started happening to me on Ubuntu after upgrading from kernel 4.19.0-16 to 4.19.0-17. Booting the old kernel works.
I assume an issue with the lxc-attach app armor profile.

**Comment by matthiasbosc** [comment]
A temporary workaround can be used to attach a container using the `--elevated-privileges` (`-e`) argument:

```shell
root@cargo:~# lxc-attach -n web
lxc-attach: web: lsm/lsm.c: lsm_process_label_set_at: 174 Operation not permitted - Failed to set AppArmor label "unconfined"
root@cargo:~# lxc-attach -e -n web
root@web:~#
```

**Comment by jfduque** [comment]
Fixed in Debian Buster's `linux-image-4.19.0-17-amd64`, version **4.19.194-2**

**Comment by stgraber** [comment]
Excellent!
I'll close the issue here as this was all sorted out externally. In my case, I haven't actually received the fixed kernel yet in our debian buster test VMs but should just be a matter of time.

**Comment by bleetsheep** [comment]
@jfduque For me it's still broken, `uname -a` reports `linux-image-4.19.0-17-amd64` like you said should be the fixed version, but then gives the version `4.19.194-1` (where you said it should be `-2`). There are no updates available for the host or guest systems. Do I need to enable backports or something like that? Looking at the packaging website, it also shows only the `-1` version: <https://packages.debian.org/buster/linux-image-4.19.0-17-amd64>. Looking at the [kernel packages category](https://packages.debian.org/buster/kernel/), I don't see anything newer available either.

How did you update in a way that fixed it? (The workaround from matthiasbosc works for me, for what it's worth.)

**Comment by matthiasbosc** [comment]
> @jfduque For me it's still broken, `uname -a` reports `linux-image-4.19.0-17-amd64` like you said should be the fixed version, but then gives the version `4.19.194-1` (where you said it should be `-2`). There are no updates available for the host or guest systems. Do I need to enable backports or something like that? Looking at the packaging website, it also shows only the `-1` version: https://packages.debian.org/buster/linux-image-4.19.0-17-amd64. Looking at the [kernel packages category](https://packages.debian.org/buster/kernel/), I don't see anything newer available either.
> 
> How did you update in a way that fixed it? (The workaround from matthiasbosc works for me, for what it's worth.)

For now, the [updated kernel](https://packages.debian.org/fr/buster-updates/linux-image-4.19.0-17-amd64) is in the `buster-updates` repo. Make sure to enable the repo on your host.

```shell
## Major bug fix updates produced after the final release of the
## distribution.
deb http://deb.debian.org/debian buster-updates main contrib non-free
#deb-src http://deb.debian.org/debian buster-updates main contrib non-free
```

**Comment by bleetsheep** [comment]
@matthiasbosc Wow thanks for the lightning quick response! I just enabled that and now see the update for the kernel image package, but will defer booting into the new kernel till tomorrow morning when I'd rather drive over in case the system doesn't come back online.
