### ISSUE TITLE
Bind mounted rootfs is writable when it should be r/o instead

### ISSUE THREAD

**Issue by minipli** [lxc/lxc#570]
It looks like LXC is prune to ["kernel bug #24912"](https://bugzilla.kernel.org/show_bug.cgi?id=24912) in regard to that it doesn't handle the `ro` mount option correctly for a bind mounted rootfs.

The following config leads to a container with a r/w rootfs while it should be r/o instead, assuming `/chroot/wheezy` is a directory containing a wheezy chroot:

> ,-[ lxc.conf ]-
> | lxc.rootfs = /chroot/wheezy
> | lxc.rootfs.options = ro
> `---

`$ lxc-execute -n wheezy -f lxc.conf /bin/bash`
`(wheezy)root@alpha:/# touch /foo`
`(wheezy)root@alpha:/# ls foo`
`foo`

The `touch /foo` should have failed.

The issue can be confirmed by stracing lxc-execute. It contains the follwing line:

> mount("/chroot/wheezy", "/chroot/jail-apps/lib/lxc/rootfs", 0x7faa280a0ca3, MS_RDONLY|MS_BIND|MS_REC, NULL) = 0

So, LXC calls `mount()` only once, to do the bind mount and apply the `ro` mount flag. But because of the behavior of the Linux kernel regarding bind mounts it ignores the `MS_RDONLY` flag and the bind mount stays writable.

Changing mount options requires a second `mount()` with the `MS_REMOUNT` flag. LXC should therefore handle this case be doing the rootfs mount in two steps:
1. bind mounting the rootfs
2. re-mount with `MS_REMOUNT | MS_BIND | MS_RDONLY`

This way the rootfs will be r/o.

**Comment by evgeni** [comment]
This should be fixed in https://github.com/lxc/lxc/commit/7c5b6e7c3524031c3e9e203a9ab3beea7efa7a41

@brauner @stgraber @hallyn please review and close if correct :)

**Comment by hallyn** [comment]
I'll buy that.  Please re-open if in fact the problem was not solved.
